version: '3.7'
services:
  db:
    build: .
    image: 'db'
    container_name: db
    restart: "always"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3309"
    environment:
      MYSQL_USER: bd
      MYSQL_ROOT_PASSWORD: nicolas1993
      MYSQL_DATABASE: facturacion
      MYSQL_PASSWORD: nicolas1993
    volumes:
      - ./sql/facturacion.sql:/docker-entrypoint-initdb.d/facturacion.sql

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'app'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  
  